algo =input('Digite algo:')
print('Qual é o tipo primitivo?', type(algo))
print('Esta tudo em maiusculo?', algo.isupper())
print('Esta tudo em minusculo?', algo.islower())
print('É somente número?', algo.isnumeric())
print('É somente letra?', algo.isalpha())
print('Começa com letra maiuscula?', algo.istitle())
print('É letra ou/e número?', algo.isalnum())
print('Foi digitado algo?', algo.isprintable())
print('Só tem espaço?', algo.isspace())
